Improve exploded JAR support, switch to AdoptOpenJDK, remove JRE build
meisterplan/docker-openjdk-springboot pull request #4
Opened 2018-12-03 15:46 UTC by xcq1

- Unify mechanism for exploded JAR and fat JAR into one automatic mechanism (Remove unnecessary duplicates)
- Better description in the README
- Switch to AdoptOpenJDK since unlike Oracle they provide on-going LTS updates for Java 10 and future public releases
- Drop support/add big warning for the JRE build since it is not necessary and not supported by AdoptOpenJDK

2018-12-03 19:26 UTC, foxylion requested changes
Overall it looks good, maybe we should just remove the deprecated images from the repository and just keep the build on Docker Hub.
This helps us also to keep the repository clean (we can remove the no longer required code).

I think most people won't see the deprecation in the log anyway.

2018-12-03 19:26 UTC, foxylion commented on run.sh
> +    sleep 10
I'm unsure if this will break some of our deployments.
Currently we do not expect that the startup can take 10 seconds longer. Maybe this will cause crash loops.

2018-12-04 08:28 UTC, xcq1 commented on run.sh
> +    sleep 10
Good point, will remove

2018-12-04 09:11 UTC, mmuth commented
LGTM

2018-12-04 09:11 UTC, merged